
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>inscription</title>
    <link rel="stylesheet" href="pageInscription.css">
</head>
<body>
    <div class="box">
        <span class="borderLine"></span>
        <form>
            <h2>Inscription</h2>
            <div class="inputBox">
                <input type="text" required="required">
                <span>nom</span>
                <i></i>
            </div>

            <div class="inputBox">
                <input type="text" required="required">
                <span>prénom</span>
                <i></i>
            </div>

            <div class="inputBox">
                <input type="text" required="required">
                <span>email</span>
                <i></i>
            </div>

            <div class="inputBox">
                <input type="text" required="required">
                <span>nom d'utilisateur</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input type="password" required="required">
                <span>mot de passe</span>
                <i></i>
            </div>

            <div class="links">
            <a href="pageConnexion.PHP">SE CONNECTER</a>
            </div>
            <input type="submit" value="inscription">
        </form>
    </div>
    
</body>
</html>