<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>connexion</title>
    <link rel="stylesheet" href="pageConnexion.css">
</head>
<body>
    <div class="box">
        <span class="borderLine"></span>
        <form>
            <h2>connexion</h2>
            <div class="inputBox">
                <input type="text" required="required">
                <span>nom d'utilisateur</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input type="password" required="required">
                <span>mot de passe</span>
                <i></i>
            </div>
        <div class="links">
            <a href="#">mot de passe oublié</a>
            <a href="pageInscription.PHP">s'inscrire</a>
        </div> 
        <input type="submit" value="connexion">
        </form>
    </div>
    
</body>
</html>